### PR TITLE
convert to vnext library and sample mvc app

### PR DESCRIPTION
**Pull request by saan800**
Hi

I converted SaasKit.Multitenancy src and MVC sample for Asp.Net5 (beta7)

I went with a completely separate library for SaasKit.Multitenancy.AspNet5 (as opposed to a backwards compatible multi framework one) as there are quite a few classes that are completely different (ie anything with HttpContext scope and IApplicationBuilder) and it ended up being a huge mess with the the framework if statements (ie "#if DNX451" thing)

Would it be possible for you to review and merge into the master, then add to nuget if you think its ok.

Thanks
Saan

### CODE REVIEW

**Comment by benfoster** [comment]
Hey @saan800 I haven't forgotten this. Just need to find time to finally upgrade to VS 2015 and review.

**Comment by saan800** [comment]
I have a more recent "rc1" version. Let me know when you have time and 2015 and I'll create a pull request for the most recent version.

**Comment by brgrz** [comment]
@saan800 Hey, make a PR now if possible, I too would like to take a look at it before I venture out on my own doing the same thing.

**Comment by benfoster** [comment]
Heads up, should have ASP.NET 5 support added in the next few days.

**Comment by saan800** [comment]
awesome
i'll double check that everything is up to date tonight (assume it is, pretty sure i got it all up there on my last update)

**Comment by benfoster** [comment]
@saan800 are you available to chat through some of the decisions you made here? Also can you send the pull request to dev branch instead?

**Pull request closed without merging**
