### PR TITLE
Add Dependencies between MemoryCache objects

### PR DESCRIPTION
**Pull request by rdefreitas**
When caching a tenant, we create cache entries for all identifiers, which is great for performance but has the downside that upon eviction, all other identifiers become invalid.

This change, suggested by @benfoster in #27 , resolves that issue by creating a cache dependency between the items. When one expires, all other related entries are removed.

I've also moved this behavior out of CreateCacheEntryOptions() so that an implementer who only wishes to make minor changes to their cache options, such as setting a sliding expiration of 15 minutes, they are not forced to re-implement the disposal code.

If an implementer wishes to disable this functionality, they can override DisposeTenantOnExpiration as follows:

`protected override bool DisposeTenantOnExpiration => false;`

### CODE REVIEW

**Comment by rdefreitas** [comment]
@benfoster this branch has been updated to include some missing fixes (samples and tests are all that's affected) from @joeaudette's PR for RTM, as well as include the RTM PR.

**Comment by benfoster** [comment]
I see you've also added a new interface `ITenant` to handle null tenants. Whilst this appears to be a positive change, can you in future submit separate PRs for different features/fixes so we can discuss them.

**Comment by rdefreitas** [comment]
@benfoster  I've separated that out to a new branch and PR.

**Comment by rdefreitas** [comment]
@benfoster I've removed the ITenant interface and will submit as a separate P/R

**Comment by rdefreitas** [comment]
@benfoster please see #37 for the null tenant feature.

**Pull request closed without merging**
